### ISSUE TITLE
The number of notes only updates on restart

### ISSUE THREAD

**Issue by nikolamilekic** [bkyle/obsidian-vault-statistics-plugin#17]
When I delete a note, the number of notes does not update in the status bar. It works fine when I add a note, but not when I delete one. I guess an even handler is missing?

I'm using the latest plugin and Obsidian versions on Windows. That is: Obsidian v1.0.2 and Vault Statistics v0.1.2.

**Comment by bkyle** [comment]
There's a [handler registered for the delete event](https://github.com/bkyle/obsidian-vault-statistics-plugin/blob/ac08a6670756e76519d7385de62f09b81fac3156/src/collect.ts#L43).  It looks like an exception is thrown when trying to [read the metadata of the non-existent file](https://github.com/bkyle/obsidian-vault-statistics-plugin/blob/ac08a6670756e76519d7385de62f09b81fac3156/src/collect.ts#L114).  There's a null-check on the returned metadata so maybe this used to return null when the file doesn't exist.  The fix should be to either confirm that the file exists or handle the exception.  I imagine that you'd see the same behaviour when you rename notes as well.

I can address this in the next update.  Thanks for pointing this out!
