### ISSUE TITLE
Feature Request: show size size of vault

### ISSUE THREAD

**Issue by chrisgrieser** [bkyle/obsidian-vault-statistics-plugin#5]
Would it be possible to show the total size of the vault? useful for example when you are syncing your vault in the cloud.

**Comment by bkyle** [comment]
Thanks for the suggestion.  I’ll add it to the next release.

**Comment by bkyle** [comment]
Included in release 0.0.5

**Comment by chrisgrieser** [comment]
Thanks a lot! (I missed the mail notifying me of the feature, somehow 😅 )

I noticed that it shows the size of all files, but not the "true" size of the vault, which is bigger when you have things in `.obsidian` (some apps save a lot of data there). And since it is that true size that matters for things like syncing, it would indeed be preferable to have that size in the status bar. 

Is that possible? I assume it's more complicated than note file sizes, so no problem at all if it's not implementable, I can surely also live without it!

**Comment by bkyle** [comment]
I wouldn't say that it's necessarily more complicated, but if you're looking for the sync-size of your vault you can get that information easily from your file manager of choice.  What's displayed is essentially the amount of content you've created or entered.
