### ISSUE TITLE
Feature Request: show total words number of vault

### ISSUE THREAD

**Issue by acsoto** [bkyle/obsidian-vault-statistics-plugin#8]
Would it be possible to display the total words number of my vault?

**Comment by bkyle** [comment]
I’d have to look into how this could be done efficiently.  I’m sure it can be done though since that information is displayed when viewing the global graph.

**Comment by acsoto** [comment]
Thanks for your reply~ ^^

**Comment by bkyle** [comment]
The implementation of this is complete and will be in the next release.

**Comment by acsoto** [comment]
Thanks a lot. However, I found that it only works in files written in English but not in Chinese. I'd like to know if it is possible to support Chinese words count?
